[package]
name = "import_shopify_data_to_postgres18"
version = "1.1.0"
edition = "2024"

[[bin]]
name = "import_shopify_data_to_postgres18"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.13.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "bigdecimal"] }
chrono = { version = "0.4", features = ["serde"] }
bigdecimal = "0.4"
generic-array = "1.3.5"
crypto-common = "0.1.7"
